site_name: Spatial Computing Project

nav:
  - Home: "index.md"
  - About: "about.md"
  - A1_Planning: 
      - Process: "A1_Planning/a1_planning_process.md"
      - Product: "A1_Planning/a1_planning_product.md"
  - A2_Configuring: 
      - Process: "A2_Configuring/a2_configuring_process.md"
      - Product: "A2_Configuring/a2_configuring_product.md"
  - A3_Massing:
      - Process: "A3_Massing/a3_massing_process.md"
      - Product: "A3_Massing/a3_massing_product.md"
  - A4_Forming:
      - Process: "A4_Forming/a4_forming_process.md"
      - Product: "A4_Forming/a4_forming_product.md"
  - Final_Deliverables: "Final_Deliverables/readme.md"
  - Index:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"
  - Quotes: "quotes.md"

theme: 
  name: material
# material
# windmill-dark
  palette:
    scheme: slate
    primary: amber
    accent: purple

plugins:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false


markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
